version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        environment:
          DB_CONFIG_URI: 'postgresql+psycopg2://example:example@localhost:5432/flask-db'
        volumes:
            - .:/code
        depends_on:
            - redis
        networks:
          - flask-application
    redis:
        image: redis
    
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_DB: flask-db
        POSTGRES_USER: example
      ports:
        - 5432:5432
      networks:
        - flask-application

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        - flask-application
networks: 
  flask-application:
    driver: bridge